summary: Organise livestream scenes

priority: major

component: Competition

milestone: $SRYYYY Competition Prep

description: >-
  The livestream requires a number of different scenes and views, made up of
  static images, video feeds, overlays etc.

  See https://studentrobotics.org/runbook/competition/livestream/scenes/.

dependencies:
  - comp/livestream/plan-video-feeds
