summary: Have livestream training sessions

priority: major

component: Competition

milestone: $SRYYYY Competition

description: >-
  Volunteers who are assigned to run the livestream should be
  trained how the system works, and how the event will be run.
